### ISSUE TITLE
OperationalError: no such table: udger_crawler_list

### ISSUE THREAD

**Issue by ntvy95** [udger/udger-python#2]
Hello,

Thank you very much for your development!

However, when I try to call udger.parse_ua, I run into this error:

`OperationalError: no such table: udger_crawler_list`

What does this imply and how can I fix it?

**Comment by skybber** [comment]
Ahoj,

tak tomu nerozumim, to vypadda, ze nema v DB tuhle tabulku, ale to nam
vsude jinde prece funguje !

lada

2017-06-30 4:34 GMT+02:00 Vy Nguyen <notifications@github.com>:

**Comment by mallat** [comment]
Hi.
It seems strange to us. How did you use SQLite databases?

**Comment by ntvy95** [comment]
No. I did not use SQLite databases because README did not mention it... I am vert sorry for the late reply.

**Comment by mallat** [comment]
Parser is designed for Udger SQLite databases available here: https://udger.com/download/data

**Comment by skybber** [comment]
Ahoj,
asi by to chtelo po podobny tipky pridat "Requirements" do README, jako je
to v jave.
lada

2017-07-11 15:59 GMT+02:00 Jaroslav Mallat <notifications@github.com>:

**Comment by pierrocknroll** [comment]
Could be great if you mention it in your Readme.
I thought it was a standalone user agent parser, it is not !
