### ISSUE TITLE
Udger parser does not work perfectly

### ISSUE THREAD

**Issue by polaris6921** [udger/udger-python#4]
I tested on the parser using python with v3 database. Though it is test database, I test a UA that is inherited in samsung phone and the result is wrong.

`{'device_brand_info_url': None, 'device_class_icon': u'phone.png', 'device_brand': None, 'ua_family_code': u'safari_mobile', 'device_class': u'Smartphone', 'device_brand_icon': None, 'device_class_code': u'smartphone', 'ua_family_icon': u'safari.png', 'ua_class_code': u'mobile_browser', 'ua_uptodate_current_version': u'', 'crawler_respect_robotstxt': None, 'device_marketname': None, 'os_code': u'android', 'device_brand_icon_big': None, 'os_icon': u'android.png', 'ua_version': '', 'ua_family_vendor': u'Apple Inc.', 'os_family': u'Android', 'ua_family_homepage': u'https://en.wikipedia.org/wiki/Safari_%28web_browser%29', 'crawler_category': None, 'device_class_info_url': u'https://udger.com/resources/ua-list/device-detail?device=Smartphone', 'crawler_last_seen': None, 'ua_family_vendor_code': u'apple_inc', 'ua_family_vendor_homepage': u'http://www.apple.com/', 'device_brand_homepage': None, 'ua_family': u'Safari mobile', 'crawler_category_code': None, 'os_info_url': u'https://udger.com/resources/ua-list/os-detail?os=Android', 'os_family_vendor': u'Google, Inc.', 'os_homepage': u'https://en.wikipedia.org/wiki/Android_%28operating_system%29', 'os_family_vendor_homepage': u'https://www.google.com/about/company/', 'os_icon_big': u'android_big.png', 'ua_version_major': '', 'os_family_vendor_code': u'google_inc', 'os_family_code': u'android', 'os': u'Android', 'device_class_icon_big': u'phone_big.png', 'device_brand_code': None, 'ua_engine': u'WebKit', 'ua_class': u'Mobile browser', 'ua_family_icon_big': u'safari_big.png', 'ua_string': 'Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG SM-G965U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36', 'ua_family_info_url': u'https://udger.com/resources/ua-list/browser-detail?browser=Safari%20mobile', 'ua': u'Safari mobile '}
`
It does not return the correct device model as well as ua_family_vendor. I wonder it is solved when using full dataset.

**Comment by mallat** [comment]
The test database is really just a test database and does not contain data.
You can see the result of your query here:  https://udger.com/resources/online-parser?Fuas=Mozilla%2F5.0+%28Linux%3B+Android+8.0.0%3B+SAMSUNG+SM-G965U+Build%2FR16NW%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+SamsungBrowser%2F9.2+Chrome%2F67.0.3396.87+Mobile+Safari%2F537.36&Fip=&test=7951&action=analyze

**Comment by polaris6921** [comment]
Thanks.
